sass:
  sass_dir: assets/css

author: BenjaminFoo
email: "benjaminfoo"

# the name of your site, e.g. ACME Corp.
title: "KCD Architect"

# this means to ignore newlines until "baseurl:"
description: "A modification which introduces advanced base-building features and new features to Kingdom Come Deliverance. "

tagline: ""

url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
